// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzipflhwwxbegfegcamh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6aXBmbGh3d3hiZWdmZWdjYW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzY2NDUsImV4cCI6MjA2NDUxMjY0NX0.-5IUQnYn6a6gWzJI1mDeg6sdU6ClOWzpWK8iIUcNa0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);